name: battlemaster
description: "A RPG battle tracker"
publish_to: "none"
version: 0.13.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  icons_plus: ^5.0.0
  ionicons: ^0.2.2
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2
  animated_flip_counter: ^0.3.4
  path_provider: ^2.1.5
  path: ^1.9.0
  scrollview_observer: ^1.23.0
  flutter_native_splash: ^2.4.2
  package_info_plus: ^8.1.0
  dio: ^5.7.0
  logger: ^2.4.0
  flutter_widget_from_html_core: ^0.15.2
  markdown: ^7.2.2
  sentry_flutter: ^8.10.0
  wiredash: ^2.3.0
  ultimate_flutter_icons: ^1.2.0
  dio_cache_interceptor: ^3.5.0
  async: ^2.11.0
  draggable_bottom_sheet: ^1.0.2
  nanoid2: ^2.0.1
  responsive_framework: ^1.5.1
  badges: ^3.1.2
  side_sheet: ^1.0.4
  http: ^1.2.2
  file_picker: ^8.1.4
  csv2json: ^0.0.3
  toastification: ^2.3.0
  file_saver: ^0.2.14
  go_router: ^14.6.1
  fingerprint: ^0.1.0
  pocketbase: ^0.19.1
  fetch_client: ^1.1.2
  pinput: ^5.0.0
  flagsmith: ^6.0.0
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/templates/templates.zip
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: ActionIcons
      fonts:
        - asset: assets/fonts/action_icons.ttf
