name: Nightly build

on:
  workflow_dispatch:

jobs:
  build:
    name: Nightly build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get
      
      - name: Generate l10n
        run: flutter gen-l10n

      - name: Activate cider
        run: flutter pub global activate cider

      - name: Bump build
        run: cider bump build

      - name: Get version
        id: get_version
        run: |
          version=$(cider version)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Generate .env
        run: |
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "PLAUSIBLE_SERVER=${{ secrets.PLAUSIBLE_SERVER }}" >> .env
          echo "PLAUSIBLE_DOMAIN=${{ secrets.PLAUSIBLE_DOMAIN }}" >> .env
          echo "WIREDASH_PROJECT=${{ secrets.WIREDASH_PROJECT }}" >> .env
          echo "WIREDASH_SECRET=${{ secrets.WIREDASH_SECRET }}" >> .env
          echo "PF2E_URI=${{ secrets.PF2E_URI }}" >> .env

      - name: Build APK
        run: flutter build apk --release --dart-define-from-file=.env

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[no ci] Update Build"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: v${{ env.VERSION }} (nightly)
          tag_name: v${{ env.VERSION }}
          files: build/app/outputs/flutter-apk/app-release.apk
